### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by PriorityDefault** [PriorityDefault/Ovo-s-Ultimate-Rustic#1]
# Textures to Add
**Blocks**
- [ ] Chain Command Block (back, conditional, front, side)
- [ ] Command Block (back, conditional, front, side)
- [ ] Frosted Ice
- [ ] Repeating Command Block (back, conditional, front, side)
- [ ] Structure Block (corner, data, load, save, base)

**Entities**
- [ ] Alex
- [ ] Polar Bear
- [ ] Boat (acacia, birch, darkoak, jungle, <s>oak</s>, spruce)
- [ ] Elytra
- [ ] End Gateway Beam
- [ ] Dragon Fireball
- [ ] Donkey
- [ ] Horse Skeleton
- [ ] Horse Zombie
- [ ] Mule
- [ ] Horse Armor (diamond, gold, iron)
- [ ] Shield Base (No Pattern)
- [ ] Stray (base + overlay)
- [ ] Sweep (I don't actually know what this is for)
- [ ] Husk
- [ ] Zombie Butcher
- [ ] Zombie Farmer
- [ ] Zombie Librarian
- [ ] Zombie Priest
- [ ] Zombie Smith
- [ ] Zombie Villager

**Items**
- [ ] Boat (acacia, birch, darkoak, jungle, <s>oak</s>, spruce)
- [ ] Banner (base + overlay)
- [ ] Broken Elytra
- [ ] Clock (format has changed)
- [ ] Compass (format has changed)
- [ ] Diamond Horse Armor
- [ ] Elytra
- [ ] Empty Armor Slots (boots, chestplate, helmet, leggings, shield)
- [ ] Gold Horse Armor
- [ ] Iron Horse Armor
- [ ] Minecart Command Block
- [ ] Structure Void

**Particle**
- [ ] Footprint

# Textures to Improve
**Blocks**
- [ ] Hardened Clay (color correction for dyes)
- [ ] Portal (I like the swirly look of the default texture)

**Entities**
- [ ] Armor Stand (darken wood)
- [ ] Ender Crystal (add runes on inner block)
- [ ] Enderdragon
- [ ] Endermite
- [ ] Shulker spark
- [ ] Wither

**GUI**
- [ ] Title (add Minecraft Realms logo)

**Items**
- [ ] Blaze Powder (animate)
- [ ] Chain Armor (boots, chestplate, helmet, leggings)
- [ ] Diamond Armor (boots, chestplate, helmet, leggings)
- [ ] Dragon Breath (animate)
- [ ] Glowstone Dust (animate)
- [ ] Gold Armor (boots, chestplate, helmet, leggings)
- [ ] Leather Armor (boots, chestplate, helmet, leggings + overlays)
- [ ] Redstone Dust (darken, animate)
- [ ] Spider Eye
- [ ] Fermented Spider Eye
- [ ] Armor Stand (darken wood)

# Other Changes
- [ ] Unify GUI elements, especially for containers
- [ ] Change paintings
